# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-31 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
