# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-11 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0003_auto_20180406_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='par_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comkids', to='solution.Comment'),
        ),
    ]
