# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-14 02:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0004_auto_20180411_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-points']},
        ),
    ]
