# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-17 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0006_auto_20180517_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='next_sect',
        ),
        migrations.RemoveField(
            model_name='section',
            name='prev_sect',
        ),
        migrations.AddField(
            model_name='module',
            name='next_sect',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right', to='solution.Module'),
        ),
        migrations.AddField(
            model_name='module',
            name='prev_sect',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left', to='solution.Module'),
        ),
    ]
