# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-17 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0007_auto_20180517_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='prev_sect',
        ),
    ]
