# Generated by Django 2.0.5 on 2018-05-18 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0009_auto_20180517_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='next_mod',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_mod', to='solution.Module'),
        ),
    ]
