# Generated by Django 2.0.5 on 2018-05-31 15:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0010_auto_20180518_0424'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueUsers', models.IntegerField(default=0)),
                ('numComments', models.IntegerField(default=0)),
                ('numVotes', models.IntegerField(default=0)),
                ('totalTime', models.DurationField(default=datetime.timedelta(0))),
                ('avgTime', models.DurationField(default=datetime.timedelta(0))),
            ],
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipHash', models.IntegerField(default=0)),
                ('timeSpent', models.DurationField(default=datetime.timedelta(0))),
                ('comments', models.IntegerField(default=0)),
                ('votes', models.IntegerField(default=0)),
                ('totalStats', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userStatList', to='solution.TotalStats')),
            ],
        ),
    ]
