# Generated by Django 2.0.5 on 2018-05-31 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0011_totalstats_userstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='lastAction',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 31, 16, 24, 14, 111407)),
        ),
    ]
