# Generated by Django 2.0.5 on 2018-05-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0012_userstats_lastaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='lastAction',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
