# Generated by Django 2.0.5 on 2018-05-31 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0013_auto_20180531_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totalstats',
            old_name='numComments',
            new_name='totalComments',
        ),
        migrations.RenameField(
            model_name='totalstats',
            old_name='numVotes',
            new_name='totalVotes',
        ),
    ]
