# Generated by Django 2.0.5 on 2018-05-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0014_auto_20180531_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='ipHash',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='lastAction',
            field=models.DateTimeField(),
        ),
    ]
