# Generated by Django 2.0.5 on 2018-05-31 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0015_auto_20180531_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='totalStats',
        ),
    ]
