# Generated by Django 2.0.6 on 2018-07-01 16:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0019_auto_20180625_0122'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipHash', models.BigIntegerField()),
                ('timeSpent', models.DurationField(default=datetime.timedelta(0))),
                ('comments', models.IntegerField(default=0)),
                ('votes', models.IntegerField(default=0)),
                ('lastAction', models.DateTimeField()),
                ('totalstats', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solution.TotalStats')),
            ],
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='totalstats',
        ),
        migrations.AddField(
            model_name='comment',
            name='created',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='created',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.DeleteModel(
            name='UserStats',
        ),
    ]
