# Generated by Django 2.0.6 on 2018-07-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0022_auto_20180701_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='projects', to='solution.Profile'),
        ),
    ]
