# Generated by Django 2.0.6 on 2018-07-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0023_auto_20180701_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
